[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { path = "../models" }
rusqlite = { version = "0.35", features = ["bundled"] }
thiserror = "2"
printpdf = "0.7"
minijinja = "2"

[dev-dependencies]
tempfile = "3"
